debug (49)

diff --git a/src/commands/add.yml b/src/commands/add.yml
--- a/src/commands/add.yml
+++ b/src/commands/add.yml
@@ -31,18 +31,23 @@ parameters:
 steps:
   - aws-cli/install
   - run:
-      environment:
-        PARAM_DESC: <<parameters.description>>
-        PARAM_PORT: <<parameters.port>>
-        PARAM_MASK: <<parameters.mask>>
-        PARAM_GROUPID: <<parameters.group-id>>
-        PARAM_TAG_KEY: <<parameters.tag-key>>
-        PARAM_TAG_VALUE: <<parameters.tag-value>>
       name: AWS whitelist add CircleCI IP
       command: >
-        source $(pwd)/src/scripts/common.sh
-        Common
-        echo "Allowing CircleCI to access port <<parameters.port>> from IP ${IP} to the security group <<parameters.group-id>>"
+        LATEST_IP=$(wget -qO- http://checkip.amazonaws.com)
+        IP="${IP-$LATEST_IP}"
+        if [ -z "${IP}" ]; then
+          echo "Could not find your public IP"
+          exit 1
+        fi
+
+        if [ -z "<<parameters.group-id>>" ]; then
+          GROUPID=$(${AWS_COMMAND} ec2 describe-security-groups \
+            --query 'SecurityGroups[].[Tags[?Key==`<<parameters.tag-key>>`] | [0].Value, GroupId]' \
+            --output text | grep ${PARAM_TAG_VALUE} | awk '{print $2}')
+          [[ -n "${GROUPID}" ]] || (echo "Could not determine Security Group ID" && exit 0);
+        fi
+
+        echo "Allowing CircleCI to access port <<parameters.port>> from IP ${IP} to the security group ${GROUPID}"
         ${AWS_COMMAND} ec2 authorize-security-group-ingress \
-          --group-id "<<parameters.group-id>>" \
+          --group-id "${GROUPID}" \
           --ip-permissions '[{"IpProtocol": "tcp", "FromPort": <<parameters.port>>, "ToPort": <<parameters.port>>, "IpRanges": [{"CidrIp": "${IP}/<<parameters.mask>>", "Description": "<<parameters.description>>"}]}]'
