test 25

diff --git a/src/commands/del.yml b/src/commands/del.yml
--- a/src/commands/del.yml
+++ b/src/commands/del.yml
@@ -32,4 +32,27 @@ steps:
   - run:
       name: Remove IP address
       command: |
-        echo "Hello, << parameters.group-id >>"
+        AWS_COMMAND="aws"
+        if [ -n "${AWS_ENDPOINT}" ];then
+          AWS_COMMAND="aws --endpoint ${AWS_ENDPOINT}"
+        fi
+
+        LATEST_IP=$(wget -qO- http://checkip.amazonaws.com)
+        IP="${IP-$LATEST_IP}"
+        if [ -z "${IP}" ]; then
+          echo "Could not find your public IP"
+          exit 1
+        fi
+
+        if [ -z "<< parameters.group-id >>" ]; then
+          GROUPID=$(${AWS_COMMAND} ec2 describe-security-groups \
+            --query 'SecurityGroups[].[Tags[?Key==`<< parameters.tag-key >>`] | [0].Value, GroupId]' \
+            --output text | grep << parameters.tag-value >> | awk '{print $2}')
+          [[ -n "${GROUPID}" ]] || (echo "Could not determine Security Group ID" && exit 0);
+          PARAM_GROUPID=${GROUPID}
+        fi
+
+        ${AWS_COMMAND} ec2 revoke-security-group-ingress \
+          --group-id "${PARAM_GROUPID}" --ip-permissions \
+          $(echo '[{"IpProtocol": "tcp", "FromPort": 443, "ToPort": 443, "IpRanges": [{"CidrIp": "", "Description": "CircleCI"}]}]' \
+            | jq -c '.[].IpRanges[].CidrIp="'${IP}/<< parameters.mask >>'"|.[].IpRanges[].Description="'<< parameters.description >>'"|.[].FromPort='<< parameters.port >>'|.[].ToPort='<< parameters.port >>'')
